language: python
python:
  - "3.7"
install:
  - pip install names
  - pip install numpy
  - pip install Global_land_mask

script:
  - cd python/test
  - python -m unittest GpsCoordinatesTest.py
  - python -m unittest RandomTest.py
