language: python
python:
  - "3.7"
install:
  - pip3 install --upgrade setuptools
  - pip3 install PyQt5
  - pip3 install --upgrade pip
  - pip3 install numpy
  - pip3 install Global_land_mask
  - pip3 install python-dateutil
  - pip3 install geopy
  - pip3 install certifi
  - pip3 install coveralls
script:
  - cd back-end
  - python -m coverage run -m unittest test/MainTest.py
after_success:
  coveralls
