language: python
python:
  - "3.7"
install:
  - pip3 install --upgrade setuptools
  - pip3 install --upgrade pip
  - pip3 install numpy
  - pip3 install Global_land_mask
  - pip3 install python-dateutil
  - pip3 install math
  - pip3 install certifi
  - pip3 install python-coveralls
script:
  - python -m coverage run -m unittest backend/test/MainTest.py
after_success:
  coveralls
