language: python
python:
  - "3.7"
install:
  - pip install names
  - pip install numpy
  - pip install Global_land_mask

script:
  - cd python
  - python -m unittest test/GpsCoordinatesTest.py
  - python -m unittest test/RandomTest.py
