language: python
python:
  - "3.7"
install:
  - pip install numpy
  - pip install Global_land_mask
  - pip install csv
  - pip install python-dateutil
  - pip install geopy
  - pip install pysqlite3

script:
  - cd python

